name: Build Android App
on:
  push:
      branches:
         - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest  # You can choose a different runner as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Display Android SDK Path
      run: |
        echo "Android SDK is located at: $ANDROID_HOME"

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Build and test the app
      run: |
        chmod +x gradlew
        chmod +x /home/runner/.gradle/wrapper/dists/gradle-2.2.1-all/6dibv5rcnnqlfbq9klf8imrndn/gradle-2.2.1/bin/gradle
        ./gradlew build
